image: docker.io/ipea7892/osf-hyoung-ffcws:pre-reg-gitpod
tasks:
    - name: Copy renv files
      command: cp -r /home/root/project/renv* /home/root/project/.Rprofile .
    - name: Launch RStudio server
      command: sudo rstudio-server start
    - name: Launch R console
      command: R
